### ISSUE TITLE
Having the option for Determining whether Value proxies should be allowed to be transported to Userspace and Back makes using the text input in the contacts list un-operational while in desktop

### ISSUE THREAD

**Issue by ScarsTRF** [art0007i/ValueProxyExtensions#1]
When having this option enabled, when I try to go and type in the text field for my contacts, selecting the text field doesn't work while on desktop making messaging unaccessible with this option enabled, only voice messages.

**Comment by art0007i** [comment]
huh really weird, because it works for me. I will try uninstalling every mod except this one and check then

**Comment by ScarsTRF** [comment]
Still is an issue, I'm running Neos Mod Settings and this mod, clicking on the input field does not result focusing to the field making it inaccessible till disabled

**Comment by GabrielSerealia** [comment]
I have the same issue with stock settings and that plugin as well.

**Comment by art0007i** [comment]
Aight I figured out what causes it, I use the [3DDashOnScreen](https://github.com/rampa3/3DDashOnScreen) mod which prevents this bug from happening. I will fix it soon.

**Comment by art0007i** [comment]
fixed in [1.1.0](https://github.com/art0007i/ValueProxyExtensions/releases/tag/1.1.0)
